# Generated by Django 4.1.4 on 2022-12-25 08:35

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='category')),
                ('slug', models.SlugField(max_length=20, null=True, unique=True, verbose_name='slug')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='tag')),
                ('slug', models.SlugField(null=True, unique=True, verbose_name='slug')),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40, verbose_name='title')),
                ('description', models.CharField(max_length=500, null=True, verbose_name='description')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='', verbose_name='thumbnail')),
                ('content', models.TextField(verbose_name='content_text')),
                ('article_body', models.CharField(max_length=3000, null=True, verbose_name='article_body')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='created_at')),
                ('updated_at', models.DateField(auto_now=True, verbose_name='updated_at')),
                ('slug', models.SlugField(blank=True, max_length=255, verbose_name='slug')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='blog.category', verbose_name='category')),
                ('tag', models.ManyToManyField(to='blog.tag', verbose_name='tag')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
