# Generated by Django 4.1.4 on 2022-12-25 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='content',
        ),
        migrations.AddField(
            model_name='article',
            name='main_text',
            field=models.TextField(blank=True, verbose_name='main_text'),
        ),
    ]
